"""OpenAPI schema customization.

FastAPI's autogenerated schema doesn't know about our bearer auth or our
RFC 7807 error contract. This module patches the schema after generation to:

1. Inject a BearerAuth security scheme and apply it globally.
2. Register the ProblemDetails component schema (RFC 7807).
3. Rewrite every 4xx/5xx response to advertise application/problem+json
   with a $ref to ProblemDetails, preserving the original description.
4. Drop FastAPI's autogenerated HTTPValidationError/ValidationError schemas,
   which are orphaned once 422 responses point at ProblemDetails instead.
"""

from __future__ import annotations

from collections.abc import Callable

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

_PROBLEM_DETAILS_SCHEMA: dict = {
    "type": "object",
    "required": ["type", "title", "status", "detail", "instance"],
    "properties": {
        "type": {"type": "string", "example": "urn:forge:error:resource-not-found"},
        "title": {"type": "string", "example": "Resource not found"},
        "status": {"type": "integer", "example": 404},
        "detail": {"type": "string", "example": "Resource type 'managed_database' not found"},
        "instance": {"type": "string", "example": "/v1/resources"},
        "errors": {
            "type": "array",
            "items": {"type": "object"},
            "description": "Per-field validation errors (422 responses only)",
        },
    },
}

_PROBLEM_RESPONSE_CONTENT = {"application/problem+json": {"schema": {"$ref": "#/components/schemas/ProblemDetails"}}}


def build_custom_openapi(application: FastAPI) -> Callable[[], dict]:
    """Return a cached openapi() function suitable for ``app.openapi = ...``."""

    def openapi() -> dict:
        if application.openapi_schema:
            return application.openapi_schema
        schema = get_openapi(
            title=application.title,
            version=application.version,
            routes=application.routes,
        )

        components = schema.setdefault("components", {})
        components["securitySchemes"] = {"BearerAuth": {"type": "http", "scheme": "bearer"}}
        schema["security"] = [{"BearerAuth": []}]

        # Register ProblemDetails and drop FastAPI's now-orphaned 422 schemas.
        components_schemas = components.setdefault("schemas", {})
        components_schemas["ProblemDetails"] = _PROBLEM_DETAILS_SCHEMA
        components_schemas.pop("HTTPValidationError", None)
        components_schemas.pop("ValidationError", None)

        # Advertise application/problem+json on every error response.
        for path_item in schema.get("paths", {}).values():
            for operation in path_item.values():
                if not isinstance(operation, dict):
                    continue
                for status_code, response in operation.get("responses", {}).items():
                    if not status_code.isdigit() or int(status_code) < 400:
                        continue
                    response["content"] = _PROBLEM_RESPONSE_CONTENT

        application.openapi_schema = schema
        return schema

    return openapi
